CREATE TABLE AllDataTypes (
  integerCol INTEGER NOT NULL IDENTITY,
  bigintCol BIGINT,
  bitCol BIT,
  decimalCol DECIMAL,
  moneyCol MONEY,
  numericCol NUMERIC,
  smallintCol SMALLINT,
  smallmoneyCol SMALLMONEY,
  tinyintCol TINYINT,
  floatCol FLOAT,
  realCol REAL,
  dateCol DATE,
  datetimeCol DATETIME,
  datetime2Col DATETIME2,
  datetimeoffsetCol DATETIMEOFFSET,
  smalldatetimeCol SMALLDATETIME,
  timeCol TIME,
  char10Col CHAR(10),
  char600Col CHAR(600),
  varchar10Col VARCHAR(10),
  varchar600Col VARCHAR(600),
  textCol TEXT,
  nchar10Col NCHAR(10),
  nchar600Col NCHAR(600),
  nvarchar10Col NVARCHAR(10),
  nvarchar600Col NVARCHAR(600),
  ntextCol NTEXT,
  binary10Col BINARY(10),
  binary600Col BINARY(600),
  varbinary10Col VARBINARY(10),
  varbinary600Col VARBINARY(600),
  imageCol IMAGE,
  timestampCol TIMESTAMP,
  uniqueidentifierCol UNIQUEIDENTIFIER,
  xmlCol XML,
  geographyCol GEOGRAPHY,
  geometryCol GEOMETRY,
  PRIMARY KEY (integerCol)
);
